---
date: "`r paste0('v',format(Sys.time(), '%y.%m.%d'))`"
output: 
  pdf_document:
    extra_dependencies: ["hanging", "fancyhdr", "datetime"]
geometry: margin=1in
urlcolor: black
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\newdateformat{mydate}{\THEYEAR.\twodigit{\THEMONTH}}

\pagestyle{fancy}
\fancyhead[LO,LE]{MD Scheuerell}
\fancyhead[CO,CE]{}
\fancyhead[RO,RE]{\textit{Curriculum vitae}}
\fancyfoot[LO,LE]{\mydate\today}
\fancyfoot[CO,CE]{}
\fancyfoot[RO,RE]{\thepage}

\thispagestyle{empty}

\renewcommand{\thefootnote}{\fnsymbol{footnote}}

\begin{center}
  \begin{Large}
  \textbf{Mark D. Scheuerell}
  \end{Large}
  
  \textit{Curriculum vitae}
\end{center}

  
# Contact

\vspace{-5pt}

School of Aquatic and Fishery Sciences \hfill 206.543.5997 (tel)  
University of Washington \hfill 206.221.6931 (fax)  
PO Box 355020 \hfill scheuerl@uw.edu  
Seattle, WA 98195-5020  \hfill https://fish.uw.edu/faculty/mark-scheuerell  


# Education

\vspace{-5pt}

Ph.D., Zoology, University of Washington (2002)

M.S., Fishery and Aquatic Science, Cornell University (1995)  

B.S., Zoology, University of Wisconsin (1991) 


# Professional appointments

\vspace{-5pt}

_Assistant Unit Leader - Fish_  
USGS Washington Cooperative Fish and Wildlife Research Unit \hfill 2019 - present

_Associate Professor_  
School of Aquatic and Fishery Sciences, University of Washington \hfill 2019 - present  

_Graduate Faculty_  
Quantitative Ecology and Resource Management, University of Washington \hfill 2019 - present  

_Affiliate Scientist_  
eScience Institute, University of Washington \hfill 2021 - present  

_Adjunct Faculty_  
School of the Environment, Washington State University \hfill 2023 - present  

_Research Fisheries Biologist_  
Northwest Fisheries Science Center, NOAA Fisheries \hfill 2003 - 2019  

_Affiliate Associate Professor_  
School of Aquatic and Fishery Sciences, University of Washington \hfill 2016 - 2019  

_Affiliate Assistant Professor_  
School of Aquatic and Fishery Sciences, University of Washington \hfill 2007 - 2016  

_Post-doctoral Fellow_  
National Research Council, National Academies of Sciences \hfill 2002 - 2003


# Fellowships

\vspace{-5pt}

National Research Council Postdoctoral Research Associateship (2003)

Ford Foundation Fellowship in Environmental Science (2002)  

National Science Foundation Graduate Research Training Grant in Mathematical Biology (1999)  

Electric Power Research Institute Fellowship in Fish Population Biology (1994)


# Awards & Honors

\vspace{-15pt}

\setlength{\parindent}{-0.375in}
\setlength{\leftskip}{0.375in}
\setlength{\parskip}{8pt}
\noindent

Presidential Early Career Award for Scientists and Engineers, White House Office of Science and Technology Policy, Washington, District of Columbia (2006)

Best Student Presentation, American Fisheries Society, Alaska Chapter Annual Meeting, Girdwood, Alaska  (2002)  

Best Student Presentation, Ecological Society of America Annual Meeting, Aquatic Section, Madison, Wisconsin (2001)  

Ingrith Deyrup-Olsen Award for Distinguished Teaching Assistant, Department of Zoology, University of Washington, Seattle, Washington (2000)  

Richard C. Snyder Award for Vertebrate Zoology Research, Department of Zoology, University of Washington, Seattle, Washington (1999)

\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}

\vspace{15pt}

# Publications

Authors in italics were students or post-docs at the time the research was completed.  

\setlength{\parindent}{-0.375in}
\setlength{\leftskip}{0.375in}
\setlength{\parskip}{8pt}
\noindent

[ _In review_ ] 

_Magel CL_, __Scheuerell MD__, Buhle ER, Lewis DJ, Weeber M, Hacker SD. In review. Estuary and upland habitats are equally important for the production of threatened Oregon Coast coho salmon populations.

[ _In press or published_ ]

73\. _Min, MA_, Cope, J, Lowry D, Selleck J, Tonnes D, Andrews K, Pacunski R, _Hennings A_, __Scheuerell MD__. 2023. Data-limited fishery assessment methods shed light on the exploitation history and population dynamics of Endangered Species Act-listed Yelloweye Rockfish in Puget Sound, Washington. Marine and Coastal Fisheries 15:

72\. Jaeger WK, __Scheuerell MD__. 2023. Return (s) on investment: Restoration spending in the Columbia River Basin and increased abundance of salmon and steelhead. PLOS One 18:e0289246

71\. _Sorel MH_, Murdoch AR, Zabel RW, Kamphaus CM, Buhle ER, __Scheuerell MD__, Converse SR. 2023. Effects of population density and environmental conditions on life‐history prevalence in a migratory fish. 2023. Ecology and Evolution 13:e10087

70\. Ward EJ, Marshall K, __Scheuerell MD__. 2022. Regularizing priors for Bayesian VAR applications to large ecological datasets. PeerJ 10:e14332

69\. _Arnold L_, __Scheuerell MD__, Busch Isaksen T. 2022. Mortality associated with extreme heat in Washington State: the historical and projected public health burden. Atmosphere 13:1392

68\. _Webster A_, Douglas T, Harms TK, Regier P, __Scheuerell MD__. 2022. Multi-scale temporal patterns in stream biogeochemistry indicate linked permafrost and ecological dynamics of boreal catchments. Ecosystems 25:1189–1206

67\. Quinn TP, __Scheuerell MD__, Losee JP, Hanada D. 2022. Multidecadal trends in body size of Puget Sound Chinook salmon: Analysis of data from the Tengu Derby, a culturally unique fishery. Marine and Coastal Fisheries 14:e10205

66\. Jankowski K, Houser JN, __Scheuerell MD__, Smits AP. 2021. Warmer winters increase phytoplankton biomass in a large floodplain river. Journal of Geophysical Research: Biogeosciences 126:e2020JG006135

65\. _McGowan DW_, Branch TA, Haught S, __Scheuerell MD__. 2021. Multi-decadal shifts in the distribution and timing of Pacific herring (_Clupea pallasii_) spawning in Prince William Sound, Alaska. Canadian Journal of Fisheries and Aquatic Sciences 78:1611-1627

64\. _DeFilippo LB_, _Buehrens TW_, __Scheuerell MD__, Kendall NW, Schindler DE. 2021. Improving short-term recruitment forecasts for coho salmon using a spatiotemporal integrated population model. Fisheries Research 242:106014

63\. __Scheuerell MD__, Ruff CP, Anderson JH, Beamer EM. 2021. An integrated population model for estimating the relative effects of natural and anthropogenic factors on a threatened population of steelhead trout. Journal of Applied Ecology 58:114-124

62\. _Siple MC_, Essington TE, Barnett LAK, __Scheuerell MD__. 2020. Limited evidence for sardine and anchovy asynchrony: re-examining an old story. Proceedings of the Royal Society B 287:20192781

61\. _Smits AP_, _Ruffing CM_, Royer TV, Appling AP, _Griffiths NA_, _Bellmore R_, __Scheuerell MD__, Harms TK, Jones J. 2019. Detecting signals of large-scale climate phenomena on river flows and nitrogen, phosphorus, and silica loads in the Mississippi-Atchafalaya River basin. Geophysical Research Letters 46:3791-3801

60\. Hampton SE, __Scheuerell MD__, Church MJ, Melack JM. 2019. Long-term perspectives in aquatic research. Limnology and Oceanography 64(S1):S2-S10

59\. Thorson JT, __Scheuerell MD__, Olden JD, Schindler DE. 2018. Spatial heterogeneity contributes more to portfolio effects than species differences in bottom-associated marine fishes. Proceedings of the Royal Society B 285:20180915

58\. Ward EJ, _Oken K_, Rose KA, Sable S, Watkins K, Holmes EE, __Scheuerell MD__. 2018. Applying spatiotemporal models to monitoring data to quantify fish responses to the Deepwater Horizon oil spill in the Gulf of Mexico. Environmental Monitoring and Assessment 190:530

57\. _Bal G_, __Scheuerell MD__, Ward EJ. 2018. Characterizing the strength of density dependence in at-risk species through Bayesian model averaging. Ecological Modelling 381:1-9

56\. _Freshwater C_, Burke BJ, __Scheuerell MD__, Grant SCH, Trudel M, Juanes F. 2018. Coherent population dynamics associated with sockeye salmon juvenile life history strategies. Canadian Journal of Fisheries and Aquatic Sciences 75:1346–1356

55\. Ardón M, Helton AM, __Scheuerell MD__, Bernhardt ES. 2017. Fertilizer legacies meet saltwater incursion: challenges and constraints for coastal plain wetland restoration. Elementa: Science of the Anthropocene 5:41

54\. _Honea JM_, McClure MM, Jorgensen JC, __Scheuerell MD__. 2016. Assessing the vulnerability of freshwater life stages of Chinook salmon to climate change. Climate Research 71:127-137

53\. _Goertler PAL_, __Scheuerell MD__, Simenstad CA, Bottom DL. 2016. Estimating common growth patterns in juvenile Chinook salmon (Oncorhynchus tshawytscha) from diverse genetic stocks and a large spatial extent. PLoS ONE 11:e0162121

52\. \footnote{All junior authors listed in alphabetical order.}Thorson JT, Ianelli JN, Larsen EA, Ries L __Scheuerell MD__, Szuwalski CS, Zipkin EF. 2016. Joint dynamic species distribution models: a tool for community ordination and spatiotemporal monitoring. Global Ecology and Biogeography 25:1144–1158

51\. _Ohlberger J_, __Scheuerell MD__, Schindler DE. 2016. Population coherence and environmental impacts across spatial scales: a case study of Chinook salmon. Ecosphere 7:e01333

50\. Jorgensen JC, Ward EJ, __Scheuerell MD__, Zabel RW. 2016. Assessing spatial covariance among time series of abundance. Ecology and Evolution 6:2472–2485

49\. __Scheuerell MD__. 2016. An explicit solution for calculating optimum spawning stock size from Ricker's stock recruitment model. PeerJ 4:e1623

48\. Thorson JT, __Scheuerell MD__, Shelton AO, See K, Skaug H, Kristensen K. 2015. Spatial factor analysis: a new tool for estimating joint species distributions and correlations in species range. Methods in Ecology and Evolution 6:627-637

47\. __Scheuerell MD__, Buhle ER, Semmens BX, Ford MJ, Cooney T, Carmichael RW. 2015. Analyzing large-scale conservation interventions with Bayesian hierarchical models: A case study of supplementing threatened Pacific salmon. Ecology and Evolution 5:2115–2125

46\. _Lisi PJ_, Schindler DE, _Cline TJ_, __Scheuerell MD__, Walsh PB. 2015. Topography and snowmelt control stream thermal sensitivity to air temperature. Geophysical Research Letters 42:3380-3388

45\. Thorson JT, __Scheuerell MD__, Semmens BX, Pattengill-Semmens C. 2014. Demographic modeling of citizen science data informs habitat preferences and population dynamics of recovering fishes. Ecology 95:3251-3258

44\. _Francis TB_, _Wolkovich EM_, __Scheuerell MD__, Katz SL, Holmes EE, Hampton SE. 2014. Shifting regimes and changing interactions in the Lake Washington, U.S.A., plankton community from 1962–1994. PLoS ONE 9(10):e110363

43\. _Griffiths JR_, Schindler DE, _Armstrong JB_, __Scheuerell MD__, Whited DC, Clarke RA, Hilborn R, Holt CA, Lindley ST, Stanford JA, Volk EC. 2014. Performance of salmon fishery portfolios across western North America. Journal of Applied Ecology 51:1554–1563

42\. Williams JG, Smith SG, Fryer J, __Scheuerell MD__, Muir WD, Flagg TA, Zabel RW, Ferguson JW, Casillas E. 2014. Influence of ocean and freshwater conditions on Columbia River sockeye salmon adult return rates. Fisheries Oceanography 23:210–224

41\. _Stachura MM_, Mantua NJ, __Scheuerell MD__. 2014. Oceanographic influences on spatio-temporal patterns in North Pacific salmon abundance. Canadian Journal of Fisheries and Aquatic Sciences 71:226-235

40\. _Thorson JT_, __Scheuerell MD__, Buhle ER, Copeland T. 2014. Spatial diversity buffers temporal variability in early juvenile survival for an endangered Pacific salmon. Journal of Animal Ecology 83:157–167

39\. Hampton SE, Holmes EE, _Scheef LP_, __Scheuerell MD__, Katz SL, _Pendleton DE_, Ward EJ. 2013. Quantifying effects of abiotic and biotic drivers on community dynamics with multivariate autoregressive (MAR) models. Ecology 94:2663–2669

38\. _Holsman KK_, __Scheuerell MD__, _Buhle ER_, Emmett R. 2012. Interacting effects of translocation, artificial propagation, and environmental conditions on the marine survival of Chinook salmon from the Columbia River, Washington, U.S.A. Conservation Biology 26:912-922 

37\. _Francis TB_, __Scheuerell MD__, Brodeur R, Levin PS, Ruzicka JJ, Tolimieri N, Peterson WT. 2012. Climate shifts the interaction web of a marine plankton community. Global Change Biology 18:2498–2508

36\. _Scheef LP_, _Pendleton DE_, Hampton SE, Katz SL, Holmes EE, __Scheuerell MD__, Johns DG. 2012. Assessing marine plankton community structure from long-term monitoring data with multivariate autoregressive (MAR) models: a comparison of fixed station versus spatially distributed sampling data. Limnology and Oceanography: Methods 10:54-64

35\. Crozier LG, __Scheuerell MD__, Zabel RW. 2011. Using time series analysis to characterize evolutionary and plastic responses to environmental change: a case study of a shift toward earlier migration date in sockeye salmon. The American Naturalist 178:755-773

34\. _Francis TB_, Schindler DE, Holtgrieve G, _Larson E_, __Scheuerell MD__, Semmens BX, Ward EJ. 2011. Habitat structure and energetic support for zooplankton in temperate lakes. Ecology Letters 14:364-372

33\. __Scheuerell MD__, Zabel RW, Sandford BP. 2009. Relating juvenile migration timing and survival to adulthood in two species of threatened Pacific salmon (Oncorhynchus spp.). Journal of Applied Ecology 46:983–990

32\. _Buhle ER_, _Holsman KK_, __Scheuerell MD__, Albaugh A. 2009. Using an unplanned experiment to evaluate the effects of hatcheries and environmental variation on threatened populations of wild salmon. Biological Conservation 142:2449–2455

31\. _Rich HB_, Quinn TP, __Scheuerell MD__, Schindler DE.  2009. Climate and intra-specific competition control the growth and life history of juvenile sockeye salmon (Oncorhynchus nerka) in Iliamna Lake, Alaska.  Canadian Journal of Fisheries and Aquatic Sciences 66:238-246

30\. Anguilletta MJ, Steel EA, Bartz KK, Kingsolver JG, __Scheuerell MD__, Beckman BR, Crozier LG. 2008. Big dams and salmon evolution: changes in thermal regimes and their potential evolutionary consequences. Evolutionary Applications 1:286-299

29\. Waples RS, Zabel RW, __Scheuerell MD__, Sanderson BL. 2008. Evolutionary responses by native species to major anthropogenic changes to their ecosystems: Pacific salmon in the Columbia River hydropower system. Molecular Ecology 17:84-96

28\. __Scheuerell MD__, _Moore JW_, Schindler DE, Harvey CJ. 2007. Varying effects of anadromous sockeye salmon on the trophic ecology of two species of resident salmonids in southwest Alaska. Freshwater Biology 52:1944-1956

27\. Hampton SE, __Scheuerell MD__, Schindler DE. 2006. Coalescence in the Lake Washington story: interaction strengths in a planktonic food web. Limnology and Oceanography 51:2042-2051

26\. __Scheuerell MD__, Hilborn R, Ruckelshaus MH, Bartz KK, Lagueux KM, Hass AD, Rawson K. 2006. The Shiraz model: a tool for incorporating anthropogenic effects and fish-habitat relationships in conservation planning. Canadian Journal of Fisheries and Aquatic Sciences 63:1596-1607

25\. Bartz KK, Lagueux KM, __Scheuerell MD__, Beechie TJ, Ruckelshaus MH. 2006. Translating restoration scenarios into habitat conditions: an initial step in evaluating recovery strategies for Chinook salmon (Oncorhynchus tshawytscha). Canadian Journal of Fisheries and Aquatic Sciences 63:1578-1595

24\. Zabel RW, __Scheuerell MD__, McClure MM, Williams JG. 2006. The interplay between climate variability and density dependence in the population viability of Chinook salmon. Conservation Biology 20:190-200

23\. _Scheuerell JM_, Schindler DE, __Scheuerell MD__, Fresh KL, Litt AH, Shepherd JA, Sibley T. 2005. Temporal dynamics in foraging behavior of a pelagic predator. Canadian Journal of Fisheries and Aquatic Sciences 62:2494-2501

22\. __Scheuerell MD__, Williams JG. 2005. Forecasting climate-induced changes in the survival of Snake River spring/summer Chinook salmon. Fisheries Oceanography 14:448-457

21\. __Scheuerell MD__. 2005. The influence of juvenile size on the age at maturity of individually-marked wild Chinook salmon. Transactions of the American Fisheries Society 134:999-1004 

20\. _Romare P_, Schindler DE, __Scheuerell MD__, _Scheuerell JM_, Litt AH, Shepherd JH. 2005. Variation in spatial and temporal gradients in zooplankton spring development: the effect of climatic factors. Freshwater Biology 50:1007-1021

19\. __Scheuerell MD__, Levin PS, Zabel RW, Williams JG, Sanderson BL. 2005. A new perspective on the importance of marine-derived nutrients to threatened stocks of Pacific salmon (Oncorhynchus sp.). Canadian Journal of Fisheries and Aquatic Sciences 62:961-964

18\. Schindler DE, Rogers DE, __Scheuerell MD__, Abrey CA. 2005. Effects of changing climate on zooplankton and juvenile sockeye salmon growth in southwestern Alaska. Ecology 86:198-209

17\. __Scheuerell MD__. 2004. Quantifying aggregation and association in three dimensional landscapes. Ecology 85:2332-2340

16\. Beauchamp DA, Sergeant CJ, Mazur MM, _Scheuerell JM_, Schindler DE, __Scheuerell MD__, Fresh KL, Seiler DE, Quinn TP. 2004. Spatial-temporal dynamics of early feeding demand and food supply by sockeye salmon fry in Lake Washington. Transactions of the American Fisheries Society 133:1014-1032

15\. __Scheuerell MD__, Schindler DE. 2004. Changes in the spatial distribution of fishes in lakes along a residential development gradient. Ecosystems 7:98-106

14\. _Moore JW_, Schindler DE, __Scheuerell MD__. 2004. Disturbance of freshwater habitats by anadromous salmon in Alaska. Oecologia 139:298-308

13\. \footnote{All junior authors listed in alphabetical order.}Hilborn R, _Branch TA_, _Ernst B_, _Magnusson A_, _Minte-Vera CV_, __Scheuerell MD__, Valero JL. 2003. State of the world’s fisheries. Annual Review of Environment and Resources 23:359-399

12\. __Scheuerell MD__, Schindler DE. 2003. Diel vertical migration by juvenile sockeye salmon: empirical evidence for the antipredation window. Ecology 84:1713-1720

11\. Schindler DE, __Scheuerell MD__, _Moore JW_, Gende SM, _Francis TB_, _Palen WJ_. 2003. Pacific salmon and the ecology of coastal ecosystems. Frontiers in Ecology and the Environment 1:31-37

10\. _Moore JW_, Schindler DE, __Scheuerell MD__, _Smith D_, Frodge J. 2003. Lake eutrophication at the urban fringe. Ambio 32:13-18

9\. __Scheuerell MD__, Schindler DE, Litt AH, Edmondson WT. 2002. Environmental and algal forcing of Daphnia production dynamics. Limnology and Oceanography 47:1477-1485

8\. Schindler DE, __Scheuerell MD__. 2002. Habitat coupling in lake ecosystems. Oikos 98:177-189

7\. Rudstam LG, Van de Valk A, __Scheuerell MD__. 2002. Comparison of acoustic and standard estimates of larval fish abundance in Oneida Lake, New York. Fisheries Research 57:145-154

6\. Delany MF, Lockley TC, Pranty B, __Scheuerell MD__. 2000. Stomach contents of two nestling Florida Grasshopper Sparrows. Florida Field Naturalist 28:75-77

5\. Perkins DW, Vickery PD, Dean TF, __Scheuerell MD__. 1998. Nesting records and reproductive success of Florida Grasshopper Sparrows (Ammodramus savannarum floridanus). Florida Field Naturalist 26:7-17.

4\. Pranty B, __Scheuerell MD__. 1997. First summer record of the Henslow’s Sparrow in Florida. Florida Field Naturalist 25:64-66

3\. Mills EL, __Scheuerell MD__, Carlton JT, Strayer DL. 1997. Biological invasions in the Hudson River: an inventory and historical analysis. Bulletin of the New York State Museum 57:1-51

2\. Mills EL, Strayer DL, __Scheuerell MD__, Carlton JT. 1996. Exotic species in the Hudson River basin: a history of invasions and introductions. Estuaries 19:814-823

1\. _He X_, \footnote{"Scheuerell" misspelled in final printing.}__Scheurell MD__, _Soranno PA_, _Wright RA_. 1994. Recurrent response patterns of a zooplankton community to whole-lake fish manipulation. Freshwater Biology 32:61-72

\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}

# Book chapters 

\vspace{-15pt}

\setlength{\parindent}{-0.375in}
\setlength{\leftskip}{0.375in}
\setlength{\parskip}{8pt}
\noindent

__Scheuerell MD__, Hilborn R. 2009. Estimating the freshwater component of essential fish habitat for Pacific salmon (_Oncorhynchus_ spp.) with the Shiraz model. Pages 187-202 in Knudsen EE, Michael H (Eds.). _Pacific Salmon Environmental and Life History Models: Advancing Science for Sustainable Salmon in the Future_. American Fisheries Society Symposium 71. Bethesda, Maryland.

Fresh KL, Graeber W, Bartz KK, Davies JR, __Scheuerell MD__, Haas A, Ruckelshaus MH, Sanderson BL. 2009. Incorporating spatial structure and diversity into recovery planning for anadromous Pacific salmonids. Pages 403-428 in Knudsen EE, Michael H (Eds.). _Pacific Salmon Environmental and Life History Models: Advancing Science for Sustainable Salmon in the Future_. American Fisheries Society Symposium 71. Bethesda, Maryland.

Dini ML, Soranno PA, __Scheuerell MD__, Carpenter SR. 1993. Effects of predators and food supply on diel vertical migration of Daphnia. Pages 153-171 in Carpenter SR, Kitchell JF (Eds.) _The Trophic Cascade in Lakes_. Cambridge University Press, Cambridge, England.

\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}


# Other publications 

\vspace{-15pt}

\setlength{\parindent}{-0.375in}
\setlength{\leftskip}{0.375in}
\setlength{\parskip}{8pt}
\noindent

Holmes EE, Ward EJ, __Scheuerell MD__. 2020. Analysis of multivariate time-series using the MARSS package, Version 3.10.12. [http://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf](http://cran.r-project.org/web/packages/MARSS/vignettes/UserGuide.pdf).

Buhle ER, __Scheuerell MD__, Cooney TD, Ford MJ, Zabel RW, Thorson JT. 2018. Using Integrated Population Models to Evaluate Fishery and Environmental Impacts on Pacific Salmon Viability. U.S. Department of Commerce, NOAA Technical Memorandum NMFS-NWFSC-140.

Schindler D, Krueger C, Bisson P, Bradford M, Clark B, Conitz J, Howard K, Jones M, Murphy J, Myers K, __Scheuerell M__, Volk E, Winton J. 2013. Arctic-Yukon-Kuskokwim Chinook Salmon Research Action Plan: Evidence of Decline of Chinook Salmon Populations and Recommendations for Future Research. Prepared for the AYK Sustainable Salmon Initiative, Anchorage, Alaska. v + 70 p.

Stout HA, Lawson PW, Bottom DL, Cooney TD, Ford MJ, Jordan CE, Kope RG, Kruzic LM, Pess GR, Reeves GH, __Scheuerell MD__, Wainwright TC, Waples RS, Ward E, Weitkamp LA, Williams JG, Williams TH. 2012. Scientific conclusions of the status review for Oregon coast coho salmon (_Oncorhynchus kisutch_). U.S. Department of Commerce, NOAA Technical Memorandum NMFS-NWFSC-118.

Peterman RM, Marmorek D, Beckman B, Bradford M, Mantua N, Riddell BE, __Scheuerell M__, Staley M, Wieckowski K, Winton JR, Wood CC. 2010. Synthesis of evidence from a workshop on the decline of Fraser River sockeye. June 15-17, 2010. Report to the Pacific Salmon Commission, Vancouver, British Columbia. 158 p.

__Scheuerell MD__. 2005. Mapping the status of Pacific salmon [book review]. Trends in Ecology & Evolution 20:290-291

Williams JG, Smith SG, Zabel RW, Muir WD, __Scheuerell MD__, Sandford BP, Marsh DM, McNatt R, Achord S. 2005. Effects of the Federal Columbia River Power System on salmonid populations. U.S. Department of Commerce, NOAA Technical Memorandum NMFS-NWFSC-63.

\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}


# Technical products 

\vspace{-15pt}

\setlength{\parindent}{-0.375in}
\setlength{\leftskip}{0.375in}
\setlength{\parskip}{8pt}
\noindent

Ward EJ, Marshall KN, __Scheuerell MD__. 2022. `{varlasso}`: An R Package for Regularized Bayesian VAR and VARSS models. R Package Version 1.1.1
https://doi.org/10.5281/zenodo.6857994

Holmes EE, Ward EJ, __Scheuerell MD__, Willis K. 2020. `{MARSS}`: Multivariate Autoregressive State-Space Modeling. R Package Version 3.10.12
https://cran.r-project.org/web/packages/MARSS/index.html

Ward EJ, __Scheuerell MD__, Holmes EE. 2018. `{atsar}`: Applied Time Series Analysis in R: An introduction to time series analysis for ecological and fisheries data with Stan. R Package Version 1.0.1
https://doi.org/10.5281/zenodo.1158021

__Scheuerell MD__. 2017. `{muti}`: An R package for computing mutual information. R Package Version 1.0.0
https://doi.org/10.5281/zenodo.439391

\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}


# Invited presentations 

\vspace{-15pt}

\setlength{\parindent}{-0.375in}
\setlength{\leftskip}{0.375in}
\setlength{\parskip}{8pt}
\noindent

Quantitative approaches for improved management and conservation of aquatic resources. School of Aquatic and Fishery Sciences, University of Washington, February 7, 2019, Seattle, Washington

Improved understanding of fisheries and ecosystems from noisy and disparate data. College of Fisheries and Ocean Sciences, University of Alaska Fairbanks, September 26, 2018, Fairbanks, Alaska

The development and application of new tools in quantitative ecology. Western Society of Naturalists Meeting, November 17, 2017, Pasadena, California

Estimating density-dependent population dynamics in a variable environment with imperfect data. Department of Fisheries and Wildlife, Oregon State University, May 1, 2017, Corvallis, Oregon

Analyzing large-scale conservation interventions with Bayesian hierarchical models: A case study of supplementing threatened Pacific salmon. American Fisheries Society Meeting, August 19, 2015, Portland, Oregon

Analyzing temporal dynamics of Pacific salmon and their ecosystems. Simon Fraser University, October 27, 2011, Burnaby, British Columbia

Great minds do not think alike: a diversity of collaborators aids in analyses of marine communities. Salish Sea Ecosystem Conference, October 25, 2011, Vancouver, British Columbia

Analyzing large-scale ecosystem experiments with Bayesian state-space models: a case study of hatcheries and Pacific salmon. American Society of Limnology and Oceanography Meeting, June 10, 2010, Santa Fe, New Mexico

An integrated approach to assessing vulnerability of Pacific salmon stocks to climate change. American Fisheries Society Annual Meeting, September 13, 2010, Pittsburgh, Pennsylvania

Evaluating large-scale effects of hatchery supplementation on threatened spring/summer Chinook salmon from the Snake River basin, USA. State of the Salmon 2010 Conference on Ecological Interactions between Wild and Hatchery Salmon, May 5, 2010, Portland, Oregon

Using stable isotopes to inform river restoration science. Western Division of the American Fisheries Society Annual Meeting, May 7, 2008, Portland, Oregon

Forecasting climate-induced shifts in the marine survival of salmon. P/ICES Conference on New Frontiers in Marine Science, June 28, 2007, Baltimore, Maryland

A sea change in the conservation of Pacific salmon: addressing climate variation and human impacts in an uncertain future. School of Aquatic and Fisheries Sciences, University of Washington, November 30, 2006, Seattle, Washington

Potential impacts of agriculture and habitat modification on Pacific Salmon. Environmental Studies Planning Unit, The Evergreen State College, November 17, 2005, Olympia, Washington

Interactive effects of climate change and human activities on the population dynamics of Pacific salmon. Department of Fisheries and Wildlife, University of Idaho, October 11, 2005, Moscow, Idaho

Estimating essential fish habitat for Pacific salmon with the Shiraz model. American Fisheries Society Annual Meeting, September 14, 2005, Anchorage, Alaska

Anthropogenic causes of a state shift in a large river ecosystem: Chinook salmon and the Snake River basin Department of Watershed Sciences, Utah State University, February 2, 2005, Logan, Utah

Tipping the scales: balancing natural and human impacts on lakes. American Society of Limnology and Oceanography DIALOG V Symposium, October 20, 2003, Bermuda Biological Station for Research

A model framework for relating life-history, freshwater habitat, and the ocean environment to Pacific salmon production and capacity. American Fisheries Society Alaska Chapter Annual Meeting, October 22, 2002, Girdwood, Alaska

Impacts of lakeshore residential development on the spatial distribution and energy sources of fishes. American Society of Limnology and Oceanography Aquatic Sciences Meeting, June 13, 2002, Victoria, British Columbia

\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}


# External support 

\vspace{-15pt}

\setlength{\parindent}{-0.375in}
\setlength{\leftskip}{0.375in}
\setlength{\parskip}{8pt}
\noindent

US National Park Service ($202k) 2022-2025. Estimating the natural range of abundance of pink salmon in the Indian River, Sitka National Historical Park. (sole PI)

Washington Sea Grant ($255k) 2022-2024. Maximizing returns on investing in barrier culvert removal in Washington State. (Co-PI with Jardine, Van Deynze, Holland, Fonner)

Washington Department of Fish and Wildlife ($100k) 2022-2023. Toxics in mussels monitoring program design. (sole PI)

US Fish and Wildlife Service ($145k) 2021-2023. Evaluating the relative effects of top-down and bottom-up factors on declines in Lake Sammamish kokanee salmon. (sole PI)

NOAA Fisheries ($135k) 2020-2023. Habitat function of shellfish aquaculture ecosystems: developing new technology to understand species use of nearshore habitats. (sole PI)

NOAA National Oceanographic Partnership Program ($199k) 2020-2023. Advancing sustainable shellfish aquaculture through machine learning and automated data collection on fish communities (co-PI with Sanderson, Ferris)

Pacific Salmon Commission Southern Boundary Restoration and Enhancement Fund ($104k) 2019-2020. Improving preseason forecasts for U.S. coho salmon management units by accounting for spatially structured temporal variation in age-at-maturity (co-PI with Schindler, Zimmerman)

North Pacific Research Board ($82k) 2017-2018. Retrospective analysis of long-term census data to identify factors affecting survival and life history strategies of coho salmon (Collaborator with Tallmon, Vulstek)

NOAA Fisheries And The Environment (FATE) Program ($147k) 2015-2016. Improving salmon population forecasts by combining environmental drivers, variable age composition, and spatial structure into hierarchical models (PI with Thorson)

Arctic-Yukon-Kuskokwim Sustainable Salmon Initiative ($340k) 2013-2014. Multivariate analysis of factors affecting AYK Chinook salmon (co-PI with Hilborn, Schindler, Mantua)

NSF-NOAA Comparative Analysis of Marine Ecosystem Organization (CAMEO) Program ($347k) 2009-2010. New statistical tools for analyzing community dynamics with applications to marine zooplankton (co-PI with Hampton, Holmes, Ward, Katz)

BPA FCRPS Biological Implementation Program ($299k) 2007-2009. Evaluating density-dependent effects of hatchery production on wild salmon (sole PI)

BPA FCRPS Biological Implementation Program ($297k) 2007-2009. Evaluating the effects of estuarine and ocean arrival timing on salmon survival from an ecosystem perspective (sole PI)

NOAA Fisheries And The Environment (FATE) Program ($118k) 2006-2007. Developing quantitative tools to forecast the effects of climate variability on the population dynamics of Pacific salmon (PI with Zabel, Mantua)

\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}


# Society membership

\vspace{-10pt}

\setlength{\parskip}{6pt}

Ecological Society of America  

\setlength{\leftskip}{0.375in}

_Secretary_, Aquatic Ecology Section (2008-2009)  

\setlength{\leftskip}{0in}

Association for the Sciences of Limnology and Oceanography  

American Fisheries Society  

\setlength{\leftskip}{0.375in}

_Chair_, Committee for the Mercer Patriarche _N Am J Fish Manag_ Best Paper Award (2006)  

\setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}


# Editorial responsibilities 

\vspace{-10pt}

\setlength{\parskip}{6pt}

Associate Editor, _Limnology and Oceanography Letters_ (2016-present)

Guest Editor, _Ecological Applications_ (2009-present)

Special Issue Editor, _Limnology and Oceanography_ (2017-2018)

Associate Editor, _Ecological Research_ (2007-2017)

Outstanding Reviewer, _Canadian Journal of Fisheries and Aquatic Sciences_ (2017)

Manuscript reviewer for

\setlength{\leftskip}{0.375in}

_Behavioural Ecology\textperiodcentered Canadian Journal of Fisheries and Aquatic Sciences\textperiodcentered Canadian Journal of Zoology\textperiodcentered Conservation Biology\textperiodcentered Ecography\textperiodcentered Ecological Applications\textperiodcentered Ecological Modelling\textperiodcentered Ecology\textperiodcentered Ecology and Society\textperiodcentered Ecology Letters\textperiodcentered Ecosphere\textperiodcentered Ecosystems\textperiodcentered Environmental Biology of Fishes\textperiodcentered Fisheries Oceanography\textperiodcentered Freshwater Biology\textperiodcentered Frontiers in Ecology and the Environment\textperiodcentered Global Change Biology\textperiodcentered Journal of Animal Ecology\textperiodcentered Journal of Applied Ecology\textperiodcentered Journal of Bioeconomics\textperiodcentered Limnology and Oceanography\textperiodcentered North American Journal of Fisheries Management\textperiodcentered Oecologia\textperiodcentered Oikos\textperiodcentered PLoS Biology\textperiodcentered PLoS ONE\textperiodcentered Proceedings of the National Academy of Sciences\textperiodcentered  Transactions of the American Fisheries Society\textperiodcentered  Trends in Ecology and Evolution_

\setlength{\leftskip}{0in}

\setlength{\parskip}{0pt}


# National & International service 

\vspace{-15pt}

\setlength{\parindent}{-0.375in}
\setlength{\leftskip}{0.375in}
\setlength{\parskip}{8pt}
\noindent

Member, U.S. Geological Survey Cooperative Research Units Diversity, Equity, and Inclusion Committee (2020-2022)

Member, Analytic and Review Team, Bull Trout Status Assessment, U.S. Fish and Wildlife Service (2020-2022)

Mentor, EcologyPlus Program from NSF INCLUDES (Inclusion across the Nation of Communities of Learners of Underrepresented Discoverers in Engineering and Science) (2018-2019)

Mentor, Ecological Society of America Early Career Ecologist Mentorship Program (2017)

Mentor, Stream Resilience Research Coordination Network, Working Group 2 - Time Series Analysis (2015-2016)

Analyst, U.S. Departments of Commerce and Justice, Deepwater Horizon Natural Resource Damage Assessment (2014-2015)

Member, Chinook Salmon Expert Panel, Arctic-Yukon-Kuskokwim Sustainable Salmon Initiative (2011-2012)

Member, Expert Advisory Panel, Pacific Salmon Commission Bilateral Scientific Workshop to Examine the Decline in Fraser River Sockeye (2010)

Member, Biological Review Team, National Marine Fisheries Service Risk Assessment of Oregon Coast Coho Salmon (2009-2010)

\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}

# University of Washington service

\vspace{-15pt}

\setlength{\parindent}{-0.375in}
\setlength{\leftskip}{0.375in}
\setlength{\parskip}{8pt}
\noindent

**College committees**

College of the Environment, Academic Grievance Committee (2020-present)

**School committees**

School of Aquatic and Fishery Sciences, Coastal Ecologist Faculty Search Committee (2022-present)

School of Aquatic and Fishery Sciences, Equity and Inclusion Committee (2021-present)

School of Aquatic and Fishery Sciences, Students Exploring Aquatic Sciences (2020-present)

Quantitative Ecology and Resource Management, Qualifying Exam Committee (2020-present)

School of Aquatic and Fishery Sciences, Curriculum Committee (2020-2022)

School of Aquatic and Fishery Sciences, Recruitment, Admission, and Scholarship Committee 
(2019-2020, 2021-2022)

School of Environmental and Forestry Sciences, Human Dimensions of Wildlife Faculty Search Committee (2020-2021)

**General service**

Future Rivers Advisory Committee (2020-present)

Fish and Wildlife Ecology Seminar Series, co-organizer (2020–2021)

Graduate School Academic Grievance Panel (2020)

Grant reviewer for Royalty Research Fund (2019, 2020)

\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}


# Teaching experience  

\vspace{-10pt}

\setlength{\parskip}{8pt}

_Best Practices in Environmental Data Science (FISH 549)_    
Instructor, University of Washington \hfill 2021 - present  

_Analysis of Ecological and Environmental Data (QERM 514)_    
Instructor, University of Washington \hfill 2020 - present  

_Applied Time Series Analysis in Fisheries and Environmental Sciences (FISH 550)_    
Co-Instructor, University of Washington \hfill 2013 - present  

_Proposal Writing and Professional Development for Graduate Students (FISH 521)_    
Instructor, University of Washington \hfill 2022  

_Applied Time Series Analyses for Ecologists_  
Visiting Instructor, Stockholm University \hfill 2014  

_Theory and Application of Stable Isotopes in Ecology (FISH 507)_  
Visiting Instructor, University of Washington \hfill 2005 - 2007

_Limnology_; _Vertebrate Zoology_; _Comparative Vertebrate Anatomy_  
Teaching Assistant, University of Washington \hfill 1997 - 2000

\setlength{\parskip}{0pt}




# Trainees

\vspace{-10pt}

\setlength{\parskip}{6pt}

__Postdoctoral scholars__

\quad Dara Farrell (2021-present)

\quad Guillaume Bal (2012-2013, co-advised with EJ Ward)

\quad Daniel Pendleton (2010-2012, co-advised with EE Holmes)

\quad Jim Thorson (2011, co-advised with EE Holmes & EJ Ward)

\quad Kirstin Holsman (2007-2010)

\quad Eric Buhle (2007-2009)

__Ph.D. students__

\quad Brian McGreal (2023-present)

\quad Markus Min (2020-present)

__M.S. students__

\quad Amirah Casey (2023-present)

\quad Tessa Code (2023-present)

\quad Nicole Doran (2021-present)

\quad Andrea Hennings (2021-present)

\quad Karl Veggerby (2021-2023)

\quad Kelly Mistry (2020-2022)

__Undergraduate students__

\quad Olivia Anderson (IBIS Undergraduate, 2023)

\quad Sarah Hensley (IBIS Undergraduate, 2023)

\quad Emily Sheppard (Undergraduate Capstone Program, 2022-2023)

\quad Amy Velasco (Undergraduate Capstone Program, 2022-2023)

\quad Jeremy Leung (Undergraduate Capstone Program, 2022)

\quad Kerrianne McCarthy (Undergraduate Capstone Program, 2019-2020)

\quad Christina Murphy (NOAA Ernest F. Hollings Undergraduate Scholar, 2007)

\setlength{\parskip}{0pt}
