---
output: pdf_document
header-includes: \pagenumbering{gobble}
geometry: margin=1in
urlcolor: black
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{center}
\textbf{Mark D. Scheuerell} \\  
USGS Washington Cooperative Fish and Wildlife Research Unit  \\
School of Aquatic and Fishery Sciences \\
University of Washington  \\
Seattle, WA 98195-5020  \\
scheuerl@uw.edu  \\
206.543.5997
\end{center}

## Education

\vspace{-5pt}

Ph.D., Zoology, University of Washington (2002)

M.S., Fishery and Aquatic Science, Cornell University (1995)  

B.S., Zoology, University of Wisconsin (1991) 


## Employment

\vspace{-5pt}

_Assistant Unit Leader_  
USGS Washington Cooperative Fish and Wildlife Research Unit \hfill 2019 - present

_Associate Professor_  
School of Aquatic and Fishery Sciences, University of Washington \hfill 2019 - present  

_Research Fisheries Biologist_  
Northwest Fisheries Science Center, NOAA Fisheries \hfill 2003 - 2019  

_Affiliate Associate Professor_  
School of Aquatic and Fishery Sciences, University of Washington \hfill 2016 - 2019  

_Affiliate Assistant Professor_  
School of Aquatic and Fishery Sciences, University of Washington \hfill 2007 - 2016  


## Professional recognition

\vspace{-5pt}

Presidential Early Career Award for Scientists and Engineers, White House Office of Science and Technology Policy, Washington, District of Columbia (2006)

Member, Ecological Society of America  

Member, Association for the Sciences of Limnology and Oceanography  

Member, American Fisheries Society  


## Graduate students and post-doctorates supervised

\vspace{-5pt}

__Post-doctoral__

\quad Guillaume Bal (2012-2013, co-advised with EJ Ward)

\quad Daniel Pendleton (2010-2012, co-advised with EE Holmes)

\quad Jim Thorson (2011, co-advised with EE Holmes & EJ Ward)

\quad Daniel Pendleton (2010-2012, co-advised with EE Holmes)

\quad Jim Thorson (2011, co-advised with EE Holmes & EJ Ward)

\quad Kirstin Holsman (2007-2010)

\quad Eric Buhle (2007-2009)

__M.S. students__

\quad Kelly Mistry, Univ Washington (2020-present)

\quad Markus Min, Univ Washington (2020-present)


## Principal publications related to this proposal

\vspace{-5pt}

\setlength{\parindent}{-0.375in}
\setlength{\leftskip}{0.375in}
\setlength{\parskip}{8pt}
\noindent

Magel C, __Scheuerell MD__, Buhle ER, Lewis DJ, Weeber M, Hacker SD. In review. Estuary and upland habitats are equally important for the production of threatened Oregon Coast coho salmon populations

DeFilippo LB, Buehrens TW, __Scheuerell MD__, Kendall NW, Schindler DE. In review. Improving short-term recruitment forecasts for coho salmon using a spatiotemporal integrated population model

__Scheuerell MD__, Ruff CP, Anderson JH, Beamer EM. 2021. An integrated population model for estimating the relative effects of natural and anthropogenic factors on a threatened population of steelhead trout. Journal of Applied Ecology 58:114-124

Thorson JT, __Scheuerell MD__, Olden JD, Schindler DE. 2018. Spatial heterogeneity contributes more to portfolio effects than species differences in bottom-associated marine fishes. Proceedings of the Royal Society B 285:20180915

Buhle ER, __Scheuerell MD__, Cooney TD, Ford MJ, Zabel RW, Thorson JT. 2018. Using Integrated Population Models to Evaluate Fishery and Environmental Impacts on Pacific Salmon Viability. U.S. Department of Commerce, NOAA Technical Memorandum NMFS-NWFSC-140.

Ward EJ, Oken K, Rose KA, Sable S, Watkins K, Holmes EE, __Scheuerell MD__. 2018. Applying spatiotemporal models to monitoring data to quantify fish responses to the Deepwater Horizon oil spill in the Gulf of Mexico. Environmental Monitoring and Assessment 190:530

Bal G, __Scheuerell MD__, Ward EJ. 2018. Characterizing the strength of density dependence in at-risk species through Bayesian model averaging. Ecological Modelling 381:1-9

Ardón M, Helton AM, __Scheuerell MD__, Bernhardt ES. 2017. Fertilizer legacies meet saltwater incursion: challenges and constraints for coastal plain wetland restoration. Elementa: Science of the Anthropocene 5:41

Honea JM, McClure MM, Jorgensen JC, __Scheuerell MD__. 2016. Assessing the vulnerability of freshwater life stages of Chinook salmon to climate change. Climate Research 71:127-137

__Scheuerell MD__, Buhle ER, Semmens BX, Ford MJ, Cooney T, Carmichael RW. 2015. Analyzing large-scale conservation interventions with Bayesian hierarchical models: A case study of supplementing threatened Pacific salmon. Ecology and Evolution 5:2115–2125

Griffiths JR, Schindler DE, Armstrong JB, __Scheuerell MD__, Whited DC, Clarke RA, Hilborn R, Holt CA, Lindley ST, Stanford JA, Volk EC. 2014. Performance of salmon fishery portfolios across western North America. Journal of Applied Ecology 51:1554–1563

Thorson JT, __Scheuerell MD__, Buhle ER, Copeland T. 2014. Spatial diversity buffers temporal variability in early juvenile survival for an endangered Pacific salmon. Journal of Animal Ecology 83:157–167


\setlength{\parindent}{0in}
\setlength{\leftskip}{0in}
\setlength{\parskip}{0pt}

